const CONFIG = {
    titleWeb: "Confession of a shy man",
    introTitle: 'Thổ thổ',
    introDesc: `Trái đất vốn lạ thường,
    Mà sao em cứ đi nhầm đường,
    Lạc vào tim anh lẻ loi,
    Đằng sau chữ yêu đây là thương`,
    btnIntro: '^^HiHi^^',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 🥰',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao em lại thích anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Thích có chút chút thôi pa <33333333',
    mess: 'Anh biết mà 🥰. Thích êm nhiều nhiều 😘😘',
    messDesc: 'A sợ mở lời làm e từ chối, nên khi nào ổn thì mình đi cafe e nhé.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/photo/?fbid=6358495897567990&set=a.647403855343918' //link mess của các bạn. VD: https://www.facebook.com/messages/t/100014188333536
}
